src/fenwicktree.rs
src/lib.rs

`FenwickTree` is added.
- The name of struct (`fenwick_tree` -> `FenwickTree`)
- Trait bound. ACL's `fenwick_tree` accepts all integer-like types whereas `FenwickTree` accepts only types that implement `Clone`, `AddAssign` and `Sub` (although all built-in integer types satisfy these constraints)

Add FenwickTree

---

Cargo.toml

`cargo publish command` would actually publish the `ac-library-rs` before <kbd>Ctrl-C</kbd> since it has no dependencies.

Add `publish = false` to prevent misoperation

---

src/internal_type_traits.rs

Separated from #14.
~~I'm not sure other modules use this in what way.~~ We want `0` or `MAX` in many modules.

Implement `internal_type_traits`

---

src/internal_type_traits.rs
src/lib.rs
src/mincostflow.rs

Port `mincostflow` from the AtCoder's library, resolved #21.
- It handles `Cap` and `Cost` as the same type. Is it better to separate types?
- => Let's keep it for now.
- It uses `Integer` trait. Does it make sense?
- => After we finished #19, let's replace the old one with the new one.
- We can change some variable names. Let me hear your opinion.

Implement mincostflow

---

src/internal_queue.rs

Add internal_queue

---

src/internal_scc.rs
src/lib.rs
src/twosat.rs

Implement twosat

---

Cargo.toml
src/convolution.rs
src/lib.rs
src/modint.rs

Implement `convolution`

---

src/mincostflow.rs

Apply fix as atcoder/ac-library#38

---

Cargo.toml

Except `readme`. (rust-lang/cargo#8277)

Add "commont metadata" to Cargo.toml

---

src/modint.rs

It is pain to add two integers as Mint:
```rust
let a = 1usize;
let b = 2usize;
let c = Mint::new(a) + Mint::new(b);
```
Thus, I implemented `Add<Rhs=int> for Mint` and `AddAssign<Rhs=int> for Mint`:
```rust
let c = Mint::new(a) + b;
```

impl binop<Rhs=int> for Mint

---

src/internal_math.rs
src/modint.rs

Benchmark:
https://gist.github.com/qryxip/c17bdb69126170900ed4333f0bf3198d

Make `modint::Barrett` `(AtomicU32, AtomicU64)`

---

src/math.rs

Add document for `math`

---

.github/workflows/ci.yml
Cargo.toml
crates/input/Cargo.toml
crates/input/src/lib.rs
examples/library-checker-convolution-mod.rs
examples/library-checker-static-range-sum.rs
examples/library-checker-sum-of-floor-of-linear.rs
examples/library-checker-unionfind.rs

https://github.com/rust-lang-ja/ac-library-rs/pull/45#issuecomment-691448964

Verify with problems from Library Checker 

---

src/dsu.rs

#75.
[Original documentation](https://atcoder.github.io/ac-library/production/document_en/dsu.html)

Update the documentation for `dsu`

---

src/convolution.rs

Fix compatibility with cargo-equip .
I believe a number of people use ac-library-rs with cargo-equip. But so far, there are some incompatibilities and they are resolved by just two bytes change of ac-library-rs. Therefore, this PR will be useful for us.
Refer the constraints  #3 in the usage of cargo-equip: https://github.com/qryxip/cargo-equip
Signed-off-by: toast-uz

Fix compatibility with cargo-equip

---

src/maxflow.rs
src/string.rs

Dependent PR:
https://github.com/rust-lang-ja/ac-library-rs/pull/109 Remove the hand-made `input!`
Related PR:
https://github.com/rust-lang-ja/ac-library-rs/pull/108 Workaround for Japanese Windows environment
https://github.com/rust-lang-ja/ac-library-rs/pull/112 u32 modulo fix
fixes:
https://rust-lang.github.io/rust-clippy/master/index.html#bool_to_int_with_if
https://rust-lang.github.io/rust-clippy/master/index.html#implicit_saturating_sub

Work clippy

---

expand.py

- Avoiding problems with incorrect encoding
`UnicodeDecodeError: 'cp932' codec can't decode byte 0x85 in position 2897: illegal multibyte sequence`
- Added option to output directly to file
PowerShell converts encoding and newline characters when passing stdout

Workaround for Japanese Windows environment

---

.github/workflows/ci.yml

* Rust 1.68 以降での、Clippy Lints のキーワードの変更 (`derive_hash_xor_eq` -> `derived_hash_with_manual_eq `) に伴うエラーを暫定的に回避します。
* https://github.com/rust-lang/rust-clippy/blob/master/CHANGELOG.md#rust-168
* https://github.com/rust-lang/rust-clippy/pull/10184
* https://rust-lang.github.io/rust-clippy/master/index.html#derived_hash_with_manual_eq
* 非推奨となっている、 Node 12 を使用していた GitHub Actions を修正します。
* `actions/checkout@v3`
* `actions/setup-python@v4`
* `actions-rs` is unmaintained:
* https://github.com/actions-rs/toolchain/issues/219
* https://github.com/actions-rs/cargo/issues/222
* Library Checker: Rust 1.60
* https://judge.yosupo.jp/help

Tentative solution for CI (Clippy error, deprecated warning)

---

.github/workflows/ci.yml

If there is a desire to move to Ubuntu 22.04 or macos-12, that may be fine as well.
> The ubuntu-18.04 environment is deprecated, consider switching to ubuntu-20.04(ubuntu-latest), or ubuntu-22.04 instead. For more details see https://github.com/actions/virtual-environments/issues/6002
- https://github.com/actions/virtual-environments/issues/6002
> The macOS-10.15 environment is deprecated, consider switching to macos-11(macos-latest), macos-12 instead. For more details see https://github.com/actions/virtual-environments/issues/5583
- https://github.com/actions/virtual-environments/issues/5583

ci: ubuntu-20.04, macos-11

---

src/scc.rs

For #75.
[Original documentation](https://atcoder.github.io/ac-library/production/document_en/scc.html)

Add document for `scc`

---

src/math.rs

This reflects atcoder/ac-library#97 .  Cherry pick of 1b48ab9 (#114).

Fix comment in `crt`

---

src/modint.rs

Uses KaTeX for modint.
If we're going to do #119, it should affect the Language Update.

Use KaTeX for modint

---

Cargo.toml

Removes `package.authors`.
This field is not deprecated yet, but is no longer used unless explicitly used for functions such as `clap`.
<https://github.com/rust-lang/rust/issues/83227>

Remove `package.authors`

---

Cargo.toml
examples/library-checker-convolution-mod.rs
examples/library-checker-static-range-sum.rs
examples/library-checker-sum-of-floor-of-linear.rs
examples/library-checker-unionfind.rs
examples/practice2_d_maxflow.rs
examples/practice2_j_segment_tree.rs
examples/practice2_k_range_affine_range_sum.rs
examples/practice2_l_lazy_segment_tree.rs
src/dsu.rs
src/math.rs
src/modint.rs
src/scc.rs
src/twosat.rs

Resolves #47.
Closes #125.
package name: `ac-library-rs` (as is)
crate name: `ac_library_rs` → **`ac_library`**

Rename the crate name to `ac_library`

---

src/lib.rs
src/segtree.rs

- Monoid BitOrOper/BitAndOper/BitXorOper: for bool/bitset type segtree data
- FromIterator: struct from Iterator
- get_slice: allows slice access to internal data
usage sample: [ABC285F - Substring of Sorted String](https://atcoder.jp/contests/abc285/tasks/abc285_f)
https://atcoder.jp/contests/abc285/submissions/38317831

Segtree: Monoid BitwiseOr/BitwiseAnd/BitwiseXor, get_slice

---

src/modint.rs

fixes https://github.com/rust-lang-ja/ac-library-rs/issues/110
This pull request includes changes to the `src/modint.rs` file to address corner cases when the modulus is set to 1. The most important changes involve modifying the initialization logic for `ModInt` and adding tests to ensure the correctness of the implementation.
Modifications to initialization logic:
* `src/modint.rs` (`pub trait ModIntBase`): Changed the initialization value in the `pow` method to handle the case when the modulus is 1.
* `src/modint.rs` (`macro_rules! impl_folding`): Updated the `Product` implementation for `StaticModInt` and `DynamicModInt` to handle the modulus being 1.
Addition of tests:
* `src/modint.rs` (`mod tests`): Added a new test `mod1_corner_case` to check the behavior of `ModInt` when the …

fix corner cases of "modint" when mod = 1

---

src/segtree.rs

This pull request fixes the FromIterator implementation for the Segtree struct. The previous implementation use Iterator::size_hint().0 to get length of the iterator. However, that is incorrect.

Fix FromIterator for Segtree

---

src/scc.rs

Resolve: #155 
This PR updates the doc comment for `SccGraph::new(n)`, correcting the description of `n` to refer to **vertices** instead of edges.  
[Original documentation](https://atcoder.github.io/ac-library/production/document_en/scc.html)

Correct `n` to refer to vertices, not edges in `SccGraph::new`

---

src/twosat.rs

Resolves #149
This PR implements the `Clone` and `Debug` traits for `TwoSat`.

Implement `Clone` and `Debug` for `TwoSat`

---

src/maxflow.rs

Resolves #150
This PR implements the `Clone` and `Debug` traits for `MfGraph` and `_Edge`.

Implement `Clone` and `Debug` for `MfGraph` and `_Edge`

---

src/maxflow.rs

Resolves #151
This PR implements the `Clone` trait for `Edge`.
As proposed in the issue, the trait is implemented using `derive`.

Implement `Clone` for `Edge`

---

src/scc.rs

Resolves #148
This PR implements the `Clone` and `Debug` traits for `SccGraph`.

Implement `Clone` and `Debug` for `SccGraph`

---

src/mincostflow.rs

Resolves #152
This PR implements the `Clone` and `Debug` traits for `MinCostFlowGraph` and `_Edge`.

Implement `Clone` and `Debug` for `MinCostFlowGraph` and `_Edge`

---

src/mincostflow.rs

Resolves #153
This PR implements the `Clone` and `Debug` traits for `MinCostFlowEdge`.

Implement `Clone` and `Debug` for `MinCostFlowEdge`

---

src/fenwicktree.rs

Related to #145
This PR implements the `Clone` trait for `FenwickTree`. 
The trait is implemented using `derive`.

Implement `Clone` for `FenwickTree`

---

src/lazysegtree.rs

Related to #143
This PR implements the `Clone` trait for `LazySegtree`.  
The trait is implemented using `derive`.
`LazySegtree` already has a `Debug` implementation, but since it is still open to discussion, this PR avoids closing the issue automatically.

Implement `Clone` for `LazySegtree`

---

src/segtree.rs

Related to #144
This PR implements the `Clone` trait for `Segtree`. 
The trait is implemented using `derive`.

Implement `Clone` for `Segtree`

---

doc/katex-header.html

- https://www.npmjs.com/package/katex

Update KaTeX to version 0.16.22

---

src/string.rs

Resolves #172
This PR reflects the changes introduced in https://github.com/atcoder/ac-library/pull/181.
However, I omitted the comparison between `sa[i]` and `0`, as it is redundant in the Rust implementation.

Add assertation in `lcp_array_arbitrary`
